### Add Todo
# @name add_todo
POST http://localhost:5000/todos HTTP/1.1
content-type: application/json

{
    "title": "Put out the trash "
}

### Get Todo
@todoId = {{add_todo.response.body.$.id}}
GET http://localhost:5000/todos/{{todoId}} HTTP/1.1

### Complete Todo
@todoId = {{add_todo.response.body.$.id}}
PUT http://localhost:5000/todos/{{todoId}}/complete HTTP/1.1

### Remove Todo
@todoId = {{add_todo.response.body.$.id}}
DELETE http://localhost:5000/todos/{{todoId}} HTTP/1.1

###
